### ISSUE TITLE
Implement `hardhat-deploy`

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet#15]
This issue involves moving the deployment script in to a task using the hardhat-deploy package: https://www.npmjs.com/package/hardhat-deploy

**Comment by rashtrakoff** [comment]
On it.

**Comment by rashtrakoff** [comment]
This comment is for utilising the code for issue #15 and issue #14 .  Issue #15 requested for creating deployment scripts but after further exploration, I found that creating tasks for deploying contracts is more suitable as tasks allow us to pass arguments from CLI. In order to use the tasks, I had to change the format of hardhat.config.js. The following paragraphs would detail the same.

1) Create a tasks folder in the contracts directory and include the tasks files in that folder (if not already done).

2) To use the tasks, you have to import them into the hardhat.config.js file in the following manner:
```
require('./tasks/DeployRinkeby');
require('./tasks/DeployPolygon');
require('./tasks/Distribute');
require('./tasks/SetRateTolerance');
require('./tasks/TransferOwnership');
require('./tasks/SetSubsidyRate');
require('./tasks/SetOracle');

```

3) Also, to use these tasks, one has to install the following packages:

```
@nomiclabs/hardhat-etherscan
hardhat-deploy
hardhat-deploy-ethers
```

When installing `hardhat-deploy-ethers` make sure that you use the following command:
 
`npm install --save-dev @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers ethers`

4) Import the packages by including the following lines into hardhat.config.js:

```
require('hardhat-deploy');
require('@nomiclabs/hardhat-etherscan');
```

5) Finally, to run the tasks, see the example code given below:

`hh DeployRinkeby --input 0x0F1D7C55A2B133E000eA10EeC03c774e0d6796e8 --output 0x745861AeD1EEe363b4AaA5F1994Be40b1e05Ff90 --router 0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506 --oracle 0xA0c5d95ec359f4A33371a06C23D89BA6Fc591A97 --requestid 1 --network rinkeby `

I believe @mikeghen this should be enough for the tasks to work. Ping me if any other errors pop up.

**Comment by mikeghen** [comment]
My mistake @rashtrakoff, I think this was happening while I was working on rexLP and just forgot to come back and close this
